name: CD-user-java

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths:
      - 'apis/user-java/**'
      - '.github/workflows/CD-user-java.yml'
      
defaults:
  run:
    working-directory: "apis/user-java"

env:
  RESOURCES_PREFIX: "team7"

jobs:
  Build-and-Push-Docker-Image: 
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    
    - name: ACR-Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.ACR_LOGIN_SERVER }}/devopsoh/api-user-java:${{ github.run_id }} --build-arg build_version=${{ github.run_id }}
    - run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/devopsoh/api-user-java:${{ github.run_id }}
          
    #Azure Login     
    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
 
 # deploy container from ACR to App Service - staging slot     
    - run: |
        az webapp config container set --name team7userjava \
        --resource-group team7rg \
        --docker-custom-image-name ${{ secrets.ACR_LOGIN_SERVER }}/devopsoh/api-user-java:${{ github.run_id }} \
        --docker-registry-server-url ${{ secrets.ACR_LOGIN_SERVER }} \
        --slot staging
        
    - name: Deploy to azure    
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'team7userjava'
        slot-name: 'staging'
        images: '${{ secrets.ACR_LOGIN_SERVER }}/devopsoh/api-user-java:${{ github.run_id }}'

    - id: healthcheck
      name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v2
      with:
        # Check the following URLs one by one sequentially
        url: https://team7userjava-staging.azurewebsites.net/api/healthcheck/user-java
        # Follow redirects, or just report success on 3xx status codes
        follow-redirect: true # Optional, defaults to "false"
        # Fail this action after this many failed attempts
        max-attempts: 60 # Optional, defaults to 1
        # Delay between retries
        retry-delay: 10s # Optional, only applicable to max-attempts > 1
        # Retry all errors, including 404. This option might trigger curl upgrade.
        retry-all: true # Optional, defaults to "false"
        
    - name: swap slots
      run: |
        az webapp deployment slot swap \
        --slot staging \
        --target-slot production \
        --name team7userjava \
        --resource-group team7rg \

    - name: Sign out of Azure
      run: |
        az logout
