name: IaCCD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

env:
  RESOURCES_PREFIX: "team7"


  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  IaCPreview:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3 # copy the repo to the runner
      
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: validate
        uses: Azure/CLI@v1
        with:
         azcliversion: 2.30.0
         inlineScript: |
          #!/bin/bash
          az deployment sub what-if --name ${{ env.RESOURCES_PREFIX }} --template-file iac/bicep/main.bicep --location ${{ secrets.LOCATION }} --parameters resourcesPrefix=${{ env.RESOURCES_PREFIX }}



  IaCDeploy:
    runs-on: ubuntu-latest
    needs: IaCPreview
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy
        uses: Azure/CLI@v1
        with:
         azcliversion: 2.30.0
         inlineScript: |
          #!/bin/bash
          az deployment sub create --name ${{ env.RESOURCES_PREFIX }} --template-file iac/bicep/main.bicep --location ${{ secrets.LOCATION }} --parameters resourcesPrefix=${{ env.RESOURCES_PREFIX }}
            

